hello: ENC[AES256_GCM,data:U9mHxYVBWg==,iv:y9HmLYNtOMVKFNIij96yglQ/sfFTNNwY2F5lGPQPdWc=,tag:EyUVFtDj7BLFgCGVZXp4wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRnRSb2FjNElBeStYZHM0
            UUhoUXFPRUVMTWJ4T1pIcytQci9CaVY2MW5rCmoraW9CMjNLZWsxL3p0a3l2UUxW
            VnZRMEpGUmJvY2tycjZ6UGZsQnB2VjgKLS0tIDhLRGxDQkJ2dVVPSEFZcnl0UTN1
            VlhUL0QyZVh2WDJONUxvRVFwNkhWMlkKF5zeoRP7EUT08m9HKi77GKKa0X/dyL+M
            2MInBu+9Vo4RYYe7j3kvAAwZR4icBnPWUJAEy2KezdJqT1J4rRVNIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14hdk3gjygvkfqz47y5ae87z0l60sda3yapj2q06pt23xfltqlf7skx5fpl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUjZFVkRqWXlubnBTNW80
            YVRjd3ZCUm1wZGxaU0E2WktUdXJKcklZQng0CjFqNjh3Z3d4R1FsQ1R4U1hrcEZp
            Wk00N0YzRTRVQkFZelZsV2VjUm1UMmMKLS0tIDNCN3N2NEJuY0dKdmp1a1Nockg4
            aExCOHMxRDVtdEI4bjlPY0FmbDY3Z2MKEHXMKhYF/7qcpDj0orgjiuB+p8zuWh/q
            GoYETSvd5Yww8CynDHwg1LQgnDkrhU8IhWN7Ovyigqx+5K2uLyay0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1698uy9t7uptyk2g8sxajt09v58rwn7xzzrespymkektr507h8f2qn8t7s8
    lastmodified: "2026-09-25T11:15:38Z"
    mac: ENC[AES256_GCM,data:vTxQJWrNl/sj231y/Xe496vd1ao0wMUOt7cbwLVLFl66GWmYZnfJ6n1Dt5D2vQ1ycpFEMM50UtMa5uC5IF4AmyAPd0S0/fCOBpHTaAdq1kG0u+SvcqshEcDvdWvNhJhM4sMeqXvs+G6kr7HePvGmrIK+3cFSNTN62711OtqMqQM=,iv:rQt0bsoDA59JvWSze1Jwcjfb+WwsekXdUDxn4WLj/Lc=,tag:huyxBLgu16XhNtMxmTB5nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
