# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.extraFiles = [ /usr/lib/firmware/edid/samsung-q800t-hdmi2.1 ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.kernelParams = [
    "zfs.zfs_arc_max=0" # Disable ARC for there's already an SSD for that
    "drm.edid_firmware=HDMI-A-1:edid/samsung-q800t-hdmi2.1" # load fake EDID
    "video=HDMI-A-1:e"
  ];
  boot.zswap = {
    enable = true;
    compressor = "lz4";
    maxPoolPercent = 30;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4b80006f-7ebf-4123-88f6-07efdda5fbe0";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5FF9-A069";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/adf805e0-0b07-4912-a394-3e75bb88bd00"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.zfs.extraPools = [ "pool" ];
  boot.zfs.forceImportRoot = false;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  services.hardware.openrgb.enable = true;
}
