# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ledoxide-reverse-proxy" = {
    image = "ghcr.io/natfrp/frpc";
    volumes = [
      "/var/lib/acme/ledoxide.zhufucdev.com/cert.pem:/run/frpc/ledoxide.zhufucdev.com.crt:ro"
      "/var/lib/acme/ledoxide.zhufucdev.com/key.pem:/run/frpc/ledoxide.zhufucdev.com.key:ro"
    ];
    cmd = [ "--disable_log_color" ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
    environmentFiles = [ /run/secrets/ledoxide/frpc.env ];
  };
  systemd.services."docker-ledoxide-reverse-proxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ledoxide-root.target"
    ];
    wantedBy = [
      "docker-compose-ledoxide-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ledoxide-server" = {
    image = "zhufucdev/ledoxide:v0.10.0";
    environment = {
      "RUST_LOG" = "info";
    };
    environmentFiles = [ /run/secrets/ledoxide/server.env ];
    volumes = [
      "/var/lib/hf-hub:/huggingface:rw"
    ];
    ports = [
      "3100:3100/tcp"
    ];
    cmd = [ "-b" "0.0.0.0:3100" ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=server"
      "--network=ledoxide_default"
    ];
  };
  systemd.services."docker-ledoxide-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ledoxide_default.service"
    ];
    requires = [
      "docker-network-ledoxide_default.service"
    ];
    partOf = [
      "docker-compose-ledoxide-root.target"
    ];
    wantedBy = [
      "docker-compose-ledoxide-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-ledoxide_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ledoxide_default";
    };
    script = ''
      docker network inspect ledoxide_default || docker network create ledoxide_default
    '';
    partOf = [ "docker-compose-ledoxide-root.target" ];
    wantedBy = [ "docker-compose-ledoxide-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ledoxide-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
