# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TORRENTING_PORT" = "6881";
      "TZ" = "Etc/UTC";
      "WEBUI_PORT" = "8080";
    };
    volumes = [
      "/mnt/pool/public:/downloads:rw"
      "qbittorent_qbittorrent-data:/config:rw"
    ];
    ports = [
      "8080:8080/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=qbittorrent"
      "--network=qbittorent_default"
    ];
  };
  systemd.services."docker-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-qbittorent_default.service"
      "docker-volume-qbittorent_qbittorrent-data.service"
    ];
    requires = [
      "docker-network-qbittorent_default.service"
      "docker-volume-qbittorent_qbittorrent-data.service"
    ];
    partOf = [
      "docker-compose-qbittorent-root.target"
    ];
    wantedBy = [
      "docker-compose-qbittorent-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-qbittorent_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f qbittorent_default";
    };
    script = ''
      docker network inspect qbittorent_default || docker network create qbittorent_default
    '';
    partOf = [ "docker-compose-qbittorent-root.target" ];
    wantedBy = [ "docker-compose-qbittorent-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-qbittorent_qbittorrent-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect qbittorent_qbittorrent-data || docker volume create qbittorent_qbittorrent-data
    '';
    partOf = [ "docker-compose-qbittorent-root.target" ];
    wantedBy = [ "docker-compose-qbittorent-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-qbittorent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
