ledoxide:
    frpc_key: ENC[AES256_GCM,data:P/GXlQWo6cXdPwq9L4gsPPhaP+9riI8Q42cXXWwyLBLnTHfMJNC7ZY4=,iv:eKrqZTPVGrJQL8y9KdVozmOE13uE3f6PE+EciryECNU=,tag:Iy4JkS0wAiu/puqeEm9yKA==,type:str]
sops:
    age:
        - recipient: age1r88ywupg9nh2y0smc36mh2mpj2gp73q5kfz2rqxaj37l37pcgexql62wjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NUw5MXdSempyczNmeDNv
            elVFa3FFd0M2dVBOK1RJTXF1SVY5TlRzdjJNCmRDcFk0WVhSZ1NVNUV3WkdGTFUv
            UjJCekJha1MxaXU2clR4SDJyZzArcjQKLS0tIG9qT2VBUzFONWlncGZiOXNqeWVW
            d2duM0JTL29FaHA1bnUxWFI4ejVhL1EKqk4ltZfWYPMzbdLlAXMpz/QlR5EnIOFz
            E324WyvamNBw2mwJdUVRLtE4ZTVD9G9q6hlt95xZMNFpXHeQz9QQKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhdz820tmka86x5r5h39fdhw35x8jpxxvpnv9krxxgne7lwrlcts4t8hax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReUk1eUswMGY4SnlVcTF6
            YkpsaVJWbVg4aWt2eDlIdFcvRmhqWCt4cmhZCk1UdkZheUJ2MlZDZW9XL3p2MTRW
            UTZvaDRPWW1XTDZCMjBpRXE1bUVLZFEKLS0tIEJhQWVibk92WGYzOCtJUDY2L0Ew
            bitDQzRFZU1vUXlSaUMxV2liWW9GUk0K+3VGPsAFMlnyVO+2FHGkII6jfJjwQQqW
            9vwcggJMj3ft7B4p560quQLm4OzmCMW7U1ZWCHXlbm6N0Nvi8qEGwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T07:55:11Z"
    mac: ENC[AES256_GCM,data:Z6ejxDGpnSrD47Y46GvnHa4ztbRslyf43A5SbHfihhnorQW9E5mG5c8YiXgrkwj7BEV2zTyi7CGEI/+rDB6nkrflLwcnNex0zq8iz7aWcItXMWHt2fB0nSy4oh0YKwsY/hsj+OQ1O89MZbNJfFIC3c1AbdsdSZ7cU1LhmOGkHVI=,iv:vJTchXmJAc0R4x1bBejE7vov9X9vKjXVjpyPcy4gf1w=,tag:jIScy4/acP+P54uuli0taA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
