ledoxide:
    frpc_key: ENC[AES256_GCM,data:P/GXlQWo6cXdPwq9L4gsPPhaP+9riI8Q42cXXWwyLBLnTHfMJNC7ZY4=,iv:eKrqZTPVGrJQL8y9KdVozmOE13uE3f6PE+EciryECNU=,tag:Iy4JkS0wAiu/puqeEm9yKA==,type:str]
sops:
    age:
        - recipient: age1r88ywupg9nh2y0smc36mh2mpj2gp73q5kfz2rqxaj37l37pcgexql62wjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVE5zZUt5ZUlBMktxckJT
            MUR5UHFoOXF6YVU3TVR4Zld0S2dmek9ZSHhBClY3SCtmZGJ2Y2sya3hyOTRuc0FQ
            N2phRE50OGVmTmJCOXlyN2FFSm9CancKLS0tIGRKYTVrOEpSc1FyRitlbEZrd2dB
            M3c1N3JDb2VuVFJjSjNuZi9mRHdHV2MKLb0ZV0aHu0uHmjtRG7PajrTmotz7p4QN
            vgZO07GyAw5aEsyWd3j7xszBmgnt/QqV4uH7WSfwxmnvzzOy1obgIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhdz820tmka86x5r5h39fdhw35x8jpxxvpnv9krxxgne7lwrlcts4t8hax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ09TN21xQ05aOVhWS3JF
            bk5ncXdXeXBWWUNiNUZiZWVtVmp1S0NNOURZCjZHTXVCaGFXSEZSK2tvOUc3c1kz
            aTh0cDl4N0o2YmY2eEVtaUp3MlY2NnMKLS0tIHpFbjhIMmE4V1N5eWgvN0ZaYW50
            dUxreGZhaEtRWTRaUVhSbkljTTNYNmcKlek4WBBqC7uJr+QnsYshoZEPQbeuP0DI
            3iCCxAhE38l762eOm9+xQuaUSPMCpb5DehX4eIGquWp3ie8BcpW0iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14hdk3gjygvkfqz47y5ae87z0l60sda3yapj2q06pt23xfltqlf7skx5fpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTWE4VzFEUUFtK2pWK2pX
            N2ltQmZ4a2ozQ1hDS3cwSm5FL2ROWXpGOUQ4Ci9KNDZvMUtKY3ByR25PZjlFRmFn
            eDJaTWZBRklPV3o3SEFHa05UOW5tVkEKLS0tIGdKNVU1ckNWVC9zZmpKRThoOFlJ
            SXFTZUVqSU9HS2ZrOU1vVkVxVkc0cHMKBrGRODftN/vOvjcaeAd28SIYjXdKXvvm
            w8OgiCJWSOQseR4DEW769gx/dmE7wJja6km72GnY09S/EdCy46z81A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T07:55:11Z"
    mac: ENC[AES256_GCM,data:Z6ejxDGpnSrD47Y46GvnHa4ztbRslyf43A5SbHfihhnorQW9E5mG5c8YiXgrkwj7BEV2zTyi7CGEI/+rDB6nkrflLwcnNex0zq8iz7aWcItXMWHt2fB0nSy4oh0YKwsY/hsj+OQ1O89MZbNJfFIC3c1AbdsdSZ7cU1LhmOGkHVI=,iv:vJTchXmJAc0R4x1bBejE7vov9X9vKjXVjpyPcy4gf1w=,tag:jIScy4/acP+P54uuli0taA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
